name: Build and Deploy Java WAR

on:
  push:
    branches:
      - main   # Adjust to your desired branch
  pull_request:
    branches:
      - main   # Adjust to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Use the appropriate Java version for your project

    - name: Set up Maven
      uses: actions/setup-maven@v3
      with:
        maven-version: '3.8.4'  # Use the desired Maven version

    - name: Build with Maven
      run: mvn clean package -DskipTests=true  # Skip tests to speed up the build, adjust if needed

    - name: Deploy Artifact
      run: |
        echo "Deploying the WAR file"
        java -jar target/*.war  # Deploy the WAR file found in the 'target' folder
